### ISSUE TITLE
ModuleNotFoundError: No module named 'configs'

### ISSUE THREAD

**Issue by senamW** [vlfom/rncdl#1]
Traceback (most recent call last):
  File "tools/train_supervised.py", line 135, in <module>
    launch(
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/wlc/ncd/RNCDL/tools/train_supervised.py", line 115, in main
    cfg = LazyConfig.load(args.config_file)
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/detectron2/config/lazy.py", line 210, in load
    exec(compile(content, filename, "exec"), module_namespace)
  File "/home/wlc/ncd/RNCDL/configs/train/fully_supervised/coco50pct.py", line 10, in <module>
    from configs.train.fully_supervised.it180k_bs16 import lr_multiplier, optimizer, train, dataloader
  File "/home/wlc/anaconda3/envs/novdet/lib/python3.8/site-packages/detectron2/config/lazy.py", line 153, in new_import
    return old_import(name, globals, locals, fromlist=fromlist, level=level)
ModuleNotFoundError: No module named 'configs'
Hello, I encountered the above error when running the supervised experiment, and I found there is no it180k_bs16 in the  configs.train.fully_supervised. Can you give me some suggestions? Thanks

**Comment by vlfom** [comment]
Dear senamW,

I am sorry for my late reply. I believe the reason for your error could be either that you are launching training from the wrong directory or you didn't set the `PYTHONPATH` environment variable, as required per our instructions.

Please, make sure you are running the main scripts from the root directory of this repository and the `PYTHONPATH` is set to the root as well. In bash (e.g. in Ubuntu systems), this would correspond to:

```bash
DETECTRON2_DATASETS=/home/azureuser/localfiles/datasets \
PYTHONPATH=$PYTHONPATH:`pwd` \
python tools/train_discovery.py \
...
```

---

Furthermore, we have just significantly revisited the ReadME file and provided much more detailed instructions on reproducing the results. We also have released the checkpoints. Please check my reply to this issue: #2 and read the ReadME file again.

Please let me know if you have any other questions.

**Comment by vlfom** [comment]
Please reopen if the issue persists.
