### ISSUE TITLE
The error during the discovery phase

### ISSUE THREAD

**Issue by slcheng97** [vlfom/rncdl#4]
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_wor
ker
    main_func(*args)
  File "/home/slcheng/Documents/code/RNCDL/tools/train_discovery.py", line 181, in main
    do_train(args, cfg)
  File "/home/slcheng/Documents/code/RNCDL/tools/train_discovery.py", line 152, in do_train
    trainer.train(start_iter, cfg.train.max_iter)
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 159, in train
    self.after_train()
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 168, in after_train
    h.after_train()
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 557, in after_train
    self._do_eval()
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 525, in _do_eval
    results = self._func()
  File "/home/slcheng/Documents/code/RNCDL/tools/train_discovery.py", line 140, in <lambda>
    hooks.EvalHook(cfg.train.eval_period, lambda: do_discovery_test(cfg, model)),
  File "/home/slcheng/Documents/code/RNCDL/tools/train_discovery.py", line 45, in do_discovery_test
    instantiate(cfg.discovery_test_loader_knowns),
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 77, in instantiate
    return cls(**cfg)
  File "/disk/work/slcheng/anaconda3/envs/pt10/lib/python3.8/site-packages/detectron2/config/config.py", line 210, in wrapped
    return orig_func(*args, **kwargs)
TypeError: build_detection_test_loader() got an unexpected keyword argument 'batch_size'
```
Hello, I encountered the above error when running the supervised experiment, and I found the funcion "build_detection_test_loader() got an unexpected keyword argument 'batch_size'". Did you know how to solve this problem? Thanks

**Comment by vlfom** [comment]
Hi chengsilin,

The problem is that you probably didn't do the inplace modifications of Detectron2 that we require. Could you please check [this section of our ReadMe file](https://github.com/vlfom/RNCDL#inplace-modifications-of-detectron2) and let me know if it works.

**Comment by slcheng97** [comment]
Thank you for your seggestions! I have sloved it now!
